### ISSUE TITLE
useless elim constraints for bridge vars

### ISSUE THREAD

**Issue by antoinevanmuylder** [antoinevanmuylder/agda#1]
When trying to prove bridge extensionality for bridges by computation (`bdgVbdg`):
```agda
  exch-bdg :
   BridgeP (λ x →  BridgeP (λ y → BB x y) (a x bi0)  (a x bi1)) (λ y → a bi0 y) (λ y → a bi1 y) →
   BridgeP (λ y →  BridgeP (λ x → BB x y) (a bi0 y)  (a bi1 y)) (λ x → a x bi0) (λ x → a x bi1)
  exch-bdg p = λ y x → p x y

  exch-bdg' :
    BridgeP (λ y →  BridgeP (λ x → BB x y) (a bi0 y)  (a bi1 y)) (λ x → a x bi0) (λ x → a x bi1) → 
    BridgeP (λ x →  BridgeP (λ y → BB x y) (a x bi0)  (a x bi1)) (λ y → a bi0 y) (λ y → a bi1 y)
  exch-bdg' p = λ x y → p y x

  -- TODO this should work but generate meaningless constraints
  bdgVbdg : ∀ p →  p ≡ (exch-bdg' (exch-bdg p) )
  bdgVbdg p = λ i → p
```
the following error occurs
```agda
Failed to solve the following constraints:
  [I$ i, I$ i₁] ~~ [I$ i, I$ i₁]
    : BridgeP (λ x → BridgeP (BB x) (a x bi0) (a x bi1)) (a bi0)
      (a bi1)
    (stuck)
```
It is an `ElimCmp ... :: Constraint` that seemingly fails to be satisfied
see `test/Succeed/BridgePrims.agda`, submodule BridgeVBridge

**Comment by antoinevanmuylder** [comment]
@Saizan what is an `ElimCmp` constraint? why is it generated and why does it fail?

**Comment by Saizan** [comment]
An  `ElimCmp` is a constraint that gets generated when comparing eliminations has to be postponed for some reason.

In this case I would expect it's because you need a case for bridge types here:
https://github.com/antoinevanmuylder/agda/blob/d281edeac893db140ab2a0ec9f42a4c1dd2efecb/src/full/Agda/TypeChecking/Conversion.hs#L858

You should also add an `equalBridge` case, to implement eta equality for bridges, around here:
https://github.com/antoinevanmuylder/agda/blob/d281edeac893db140ab2a0ec9f42a4c1dd2efecb/src/full/Agda/TypeChecking/Conversion.hs#L323
